name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Heroku stack to container
        run: |
          curl -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }} \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -H "Content-Type: application/json" \
          -d '{"build_stack":"container"}'

      - name: Build and Deploy Docker container
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
